# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."encrypted_maindisk".device = "/dev/disk/by-id/ata-ST9320423AS_5VH4K9GD";

  fileSystems."/" =
    { device = "/dev/disk/by-partlabel/disk-maindisk-root";
      fsType = "btrfs";
      options = [ "subvol=rootfs" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-partlabel/disk-maindisk-ESP";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-partlabel/disk-maindisk-root";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-partlabel/disk-maindisk-root";
      fsType = "btrfs";
      options = [ "subvol=persist" ];
    };

  fileSystems."/.swapvol" =
    { device = "/dev/disk/by-partlabel/disk-maindisk-root";
      fsType = "btrfs";
      options = [ "subvol=swap" ];
    };

  swapDevices =
    [ { device = "/.swapvol/swapfile"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s25.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/disk/by-id/ata-ST9320423AS_5VH4K9GD";
  networking.hostName = "X201";
}
